name: Push

on: push

jobs:
  test:
    name: Lint, build, and test on node 24.x and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Use Node.js 24.x
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@3e063b974f0d209807684aa23e534b3dde517fd9 # v1.11.2
      - name: Lint codebase
        run: yarn lint
      - name: Build codebase
        run: yarn build
      - name: Test codebase
        run: yarn test --coverage
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
